<?xml version="1.0"?>
<package format="3">
  <name>quadruped_bringup</name>
  <version>0.0.1</version>
  <description>Bringup launch files for quadruped robot</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>autoware_ndt_scan_matcher</exec_depend>
  <exec_depend>autoware_ekf_localizer</exec_depend>
  <exec_depend>fast_lio</exec_depend>
</package>
